name: cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyter-book
  - jupyterlab
  - geocat-datafiles
  - sphinx-pythia-theme
  - numpy
  - xarray
  - nodejs
  - matplotlib
  - pandas
  - scipy
  - pywavelets
